### ISSUE TITLE
Error in creation of NetworkConnect filters

### ISSUE THREAD

**Issue by denied39** [darkoperator/Posh-Sysmon#1]
When I try to create a NetworkConnect filter, the resulting xml file has "endwith" as the condition, instead of "end with". It looks like lines 237 and 263 of posh-sysmon.psm1 have $Condition, but they should be $ConditionString. 

`$Filter.SetAttribute('condition',$Condition)`

**Comment by darkoperator** [comment]
Thanks for reporting it, you are right will fix and push an update soon

**Comment by denied39** [comment]
Awesome! Thanks for the tool!

**Comment by denied39** [comment]
Change works. Thanks again.
