### ISSUE TITLE
Filter Creation Failed

### ISSUE THREAD

**Issue by adimenia** [darkoperator/Posh-Sysmon#5]
Hello, im trying to create a ProcessAccessFilter for lsass.exe and this is the output i get
Command: New-SysmonProcessAccessFilter -Path .\ProcessCreate.xml -OnMatch include -Condition Contains -EventField TargetImage lsass.exe -Verbose
Output: VERBOSE: Mutiple nodes.

when i use Get-SysmonRule on that config file here is what i get

EventType     : ProcessCreate
Scope         : All Events
DefaultAction : Exclude
Filters       :

no filter was applied.

**Comment by darkoperator** [comment]
You need to either change the rule to include or add a rule with an action of include, you can use set-sysmonrule to change the defaultaction

**Comment by adimenia** [comment]
isnt that what i was doing? New-SysmonProcessAccessFilter -Path .\ProcessCreate.xml -**OnMatch include** -Condition Contains -EventField TargetImage lsass.exe -Verbose

**Comment by darkoperator** [comment]
The rule has to exist first. It is first config file, event type rule and then filter in specified rule

**Comment by adimenia** [comment]
I might be missing something, i have managed to change the default action to include. but doesn't matter what i try i cant create a filter. here are some more examples.
 ew-SysmonFileCreateFilter -Path .\ProcessCreate.xml -Condition Contains -EventField TargetFilename lsass.exe -OnMatch include -Verbose

Output: VERBOSE: Mutiple nodes.

Get-SysmonRule -Path .\ProcessCreate.xml

Output: EventType     : ProcessCreate
	Scope         : All Events
	DefaultAction : Include
	Filters       :

is it possible to see a working example? im trying to follow the examples on  your blog post: http://www.darkoperator.com/blog/2017/2/17/posh-sysmon-powershell-module-for-creating-sysmon-configuration-files but cant seem to get them to work.

**Comment by darkoperator** [comment]
Again use error you are creating a FileCreate Filter and there is only a Process Create Rule and not File Create one. 

example of proper use
```PowerShell
PS C:\Users\Carlos\Desktop> New-SysmonConfiguration -Path .\process_open_example.xml -HashingAlgorithm SHA256 -ProcessAccess
PS C:\Users\Carlos\Desktop> Set-SysmonRule -EventType ProcessAccess -OnMatch Include -Action Modify -Path .\process_open_example.xml


EventType     : ProcessAccess
Scope         : All Events
DefaultAction : Include
Filters       :



PS C:\Users\Carlos\Desktop> New-SysmonProcessAccessFilter -Path '.\process_open_example.xml' -OnMatch include -Condition Contains -EventField TargetImage -Value 'lssas.exe'


EventType     : ProcessAccess
Scope         : Filtered
DefaultAction : Include
Filters       : {@{EventField=TargetImage; Condition=contains; Value=lssas.exe}}
```

you need the proper rule before creating a filter, filter cmdlets DO NOT create or add rules if they do not exist. Will add a terminating error for this in the next release so user get a red error message aying no rule is create or rule found with default action specified.

**Comment by adimenia** [comment]
Oh,  now its clear,  thanks a lot!!!

**Comment by darkoperator** [comment]
Can I close the issue?

**Comment by darkoperator** [comment]
closing for now. you can re-open if problem persists
